name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bash-version: ['4.4', '5.0', '5.1']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bash ${{ matrix.bash-version }}
      run: |
        if [ "${{ matrix.bash-version }}" != "$(bash --version | head -n1 | grep -o '[0-9]\+\.[0-9]\+')" ]; then
          echo "Using system bash version: $(bash --version | head -n1)"
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl php-cli

    - name: Verify script permissions
      run: |
        ls -la bin/
        ls -la tests/

    - name: Run tests
      run: |
        ./tests/run_tests.sh

    - name: Test installation process
      run: |
        # Test the installation in a temporary directory
        TEMP_PREFIX="/tmp/terminus-vm-install-test"
        mkdir -p "$TEMP_PREFIX"
        PREFIX="$TEMP_PREFIX" ./install.sh

        # Verify files were installed
        ls -la "$TEMP_PREFIX/bin/"
        test -x "$TEMP_PREFIX/bin/terminus"
        test -x "$TEMP_PREFIX/bin/terminus-vm"

        # Test basic functionality with installed version
        export PATH="$TEMP_PREFIX/bin:$PATH"
        terminus help | grep -q "Terminus Version Manager"
        terminus path | grep -q "/tmp"

        echo "✅ Installation test passed"

    - name: Test with different PHP versions
      run: |
        # Test with different PHP binaries if available
        for php_bin in php php7.4 php8.0 php8.1 php8.2; do
          if command -v "$php_bin" >/dev/null 2>&1; then
            echo "Testing with $php_bin"
            TERMINUS_PHP="$php_bin" ./bin/terminus help | grep -q "Terminus Version Manager"
            echo "✅ $php_bin works"
          fi
        done

  test-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install PHP
      run: |
        brew install php

    - name: Run tests
      run: |
        ./tests/run_tests.sh

    - name: Test installation on macOS
      run: |
        TEMP_PREFIX="/tmp/terminus-vm-install-test"
        mkdir -p "$TEMP_PREFIX"
        PREFIX="$TEMP_PREFIX" ./install.sh

        export PATH="$TEMP_PREFIX/bin:$PATH"
        terminus help | grep -q "Terminus Version Manager"

        echo "✅ macOS installation test passed"
